title: Hellp-World
description: >-
  Deze Repository is opgemaakt in de geest van een assignment ten name van
  Sentia, het is de bedoeling om een zo breed mogelijke inzicht te in mijn denk
  vermogen te beitelen.
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
